server:
  shutdown: immediate

aws:
  provider: localstack

sqs:
  endpoint.url: http://localhost:4566

oauth:
  endpoint.url: http://localhost:8090/auth

prison:
  endpoint.url: http://localhost:8081

court.register:
  endpoint.url: http://localhost:8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
