hmpps.sqs:
  provider: localstack
  queues:
    registers:
      queueName: hmpps_registers_to_nomis_queue
      dlqName: hmpps_registers_to_nomis_dlq
      subscribeTopicId: domainevents
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps_domain_events
