---
# Values here are the same across all environments
generic-service:
  nameOverride: hmpps-registers-to-nomis-update

  image:
    repository: quay.io/hmpps/hmpps-registers-to-nomis-update
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/custom-http-errors: "418"
    tlsSecretName: hmpps-registers-to-nomis-update-cert
    path: /

  env:
    SERVER_PORT: 8080
    JAVA_OPTS: "-Xmx512m"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    SPRING_PROFILES_ACTIVE: "logstash"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-registers-to-nomis-update:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      HMPPS_AUTH_CLIENT_CLIENT_ID: "OAUTH_CLIENT_ID"
      HMPPS_AUTH_CLIENT_CLIENT_SECRET: "OAUTH_CLIENT_SECRET"
    sqs-nomis-update-secret:
      HMPPS_SQS_QUEUES_REGISTERS_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_REGISTERS_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_REGISTERS_QUEUE_NAME: "sqs_queue_name"
    sqs-nomis-update-dl-secret:
      HMPPS_SQS_QUEUES_REGISTERS_DLQ_NAME: "sqs_queue_name"
      HMPPS_SQS_QUEUES_REGISTERS_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_REGISTERS_DLQ_SECRET_ACCESS_KEY: "secret_access_key"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-registers-to-nomis-update
