---
# Environment specific values, override helm_deploy/hmpps-registers-to-nomis-update/values.yaml

generic-service:
  replicaCount: 4
  ingress:
    host: registers-to-nomis-update-preprod.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://api-preprod.prison.service.justice.gov.uk"
    COURT_REGISTER_ENDPOINT_URL: "https://court-register-preprod.hmpps.service.justice.gov.uk"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
