---
# Environment specific values, override helm_deploy/hmpps-registers-to-nomis-update/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: registers-to-nomis-update-dev.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://api-dev.prison.service.justice.gov.uk"
    COURT_REGISTER_ENDPOINT_URL: "https://court-register-dev.hmpps.service.justice.gov.uk"
    # Whether to apply the changes to Nomis
    APPLY_CHANGES: "true"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
