---
# Environment specific values, override helm_deploy/hmpps-registers-to-nomis-update/values.yaml

generic-service:
  replicaCount: 4
  ingress:
    host: registers-to-nomis-update.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://api.prison.service.justice.gov.uk"
    COURT_REGISTER_ENDPOINT_URL: "https://court-register.hmpps.service.justice.gov.uk"
    # Whether to apply the changes to Nomis
    APPLY_CHANGES: "false"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: digital-prison-service

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
