---
# Environment specific values, override helm_deploy/hmpps-registers-to-nomis-update/values.yaml

generic-service:
  ingress:
    host: registers-to-nomis-update.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://api.prison.service.justice.gov.uk"
    COURT_REGISTER_ENDPOINT_URL: "https://court-register.hmpps.service.justice.gov.uk"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: syscon
